In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from google.colab import drive
drive.mount ('/content/drive')

Mounted at /content/drive


In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [3]:
train = pd.read_csv('/content/drive/MyDrive/WOC 4 (2).0/Polynomial_train.csv')
train.head()

Unnamed: 0         X         Y         Z       label
0           0  0.643715 -9.866550 -5.836019  307.972927
1           1 -1.366446 -3.761945 -8.756162  136.398375
2           2 -4.090270 -1.836218 -1.846066 -310.724813
3           3 -8.730478 -1.923651  3.892972    1.755447
4           4  5.367169  0.358357  6.703989 -343.582590

In [4]:
normalized_dataset = (train - np.min(train)) / (np.max(train) - np.min(train))
X = normalized_dataset.iloc[:,1:4]
Y = normalized_dataset.iloc[:,4]

X_train=X.to_numpy()
Y_train=Y.to_numpy()

m=Y_train.shape[0]
X_train=np.c_[np.ones(m),X_train]
Y_train= Y_train.reshape(X_train.shape[0],1)

print(X_train.shape)
print(Y_train.shape)

(50000, 4)
(50000, 1)


In [5]:
X=X_train.astype('float') 
Y=Y_train.astype('float')


In [6]:
for i in range(X.shape[0]):
    for j in range(X.shape[1]):
        X[i][j]=X[i][j]**(j+1)

print(X)

theta = np.matmul(np.linalg.inv( np.matmul(X.T,X) ), np.matmul(X.T,Y))
print(theta)

[[1.00000000e+00 5.37430616e-02 2.38504028e-07 1.96651560e-03]
 [1.00000000e+00 3.53600734e-02 2.26353088e-02 1.78678530e-05]
 [1.00000000e+00 1.65677827e-02 5.07161920e-02 2.81147888e-02]
 ...
 [1.00000000e+00 1.30987945e-01 3.41162118e-02 5.15009607e-02]
 [1.00000000e+00 8.72050764e-02 2.84456906e-01 4.64392044e-03]
 [1.00000000e+00 5.35384120e-02 6.25193931e-01 1.34327645e-02]]
[[ 0.42609571]
 [ 0.03771512]
 [-0.03058842]
 [ 0.02619314]]


In [7]:
y_pred=np.matmul(X,theta)
print(y_pred)

[[0.42817414]
 [0.42673741]
 [0.42590566]
 ...
 [0.43134135]
 [0.42080522]
 [0.40934308]]


In [8]:
X[:,0]
print(X)

[[1.00000000e+00 5.37430616e-02 2.38504028e-07 1.96651560e-03]
 [1.00000000e+00 3.53600734e-02 2.26353088e-02 1.78678530e-05]
 [1.00000000e+00 1.65677827e-02 5.07161920e-02 2.81147888e-02]
 ...
 [1.00000000e+00 1.30987945e-01 3.41162118e-02 5.15009607e-02]
 [1.00000000e+00 8.72050764e-02 2.84456906e-01 4.64392044e-03]
 [1.00000000e+00 5.35384120e-02 6.25193931e-01 1.34327645e-02]]


In [9]:
test=pd.read_csv('/content/drive/MyDrive/WOC 4 (2).0/Polynomial_test.csv')
test.head()


Unnamed: 0         X         Y         Z        label
0           0  9.322078  0.413096  5.984731  -657.669309
1           1  2.811964  6.142752  6.419237  -545.362524
2           2 -2.669784  7.775091 -6.931907   -75.044187
3           3 -6.992156 -9.205548  0.852580 -2403.124902
4           4  1.574294 -2.213266  6.029188     8.595325

In [10]:
normalized_dataset = (test - np.min(test)) / (np.max(test) - np.min(test))
X = normalized_dataset.iloc[:,1:4]
Y = normalized_dataset.iloc[:,4]

X_test=X.to_numpy()
Y_test=Y.to_numpy()

m=Y_test.shape[0]
X_test=np.c_[np.ones(m),X_test]
Y_test= Y_test.reshape(X_test.shape[0],1)

In [11]:
X=X_test.astype('float') 
Y=Y_test.astype('float')


In [12]:
for i in range(X.shape[0]):
    for j in range(X.shape[1]):
        X[i][j]=X[i][j]**(j+1)

print(X)


[[1.00000000e+00 9.33393090e-01 1.41227666e-01 4.08315769e-01]
 [1.00000000e+00 4.10377139e-01 5.26206590e-01 4.54557754e-01]
 [1.00000000e+00 1.34330232e-01 7.02532325e-01 5.53703803e-04]
 ...
 [1.00000000e+00 6.92331275e-01 6.00034873e-01 2.77355845e-01]
 [1.00000000e+00 3.49218107e-02 1.81592477e-01 8.55635462e-03]
 [1.00000000e+00 8.36322688e-01 1.11645328e-01 1.34013973e-01]]


In [13]:
y_pred=np.matmul(X,theta)
print(y_pred)

[[0.46767389]
 [0.43738361]
 [0.40968715]
 ...
 [0.44111778]
 [0.42208229]
 [0.45773292]]


In [14]:
mean_y_pred=np.mean(y_pred)*np.ones(1)
mean_Y=np.mean(Y)*np.ones(1)
accuracy=np.sum(np.square(y_pred - mean_y_pred)) / np.sum(np.square(Y-mean_Y))*100
print(accuracy)

1.306370114794607
